swagger: '2.0'
info:
  title: Query Tool API
  version: "0.1"
  description: An API that returns a snippet from an academic publication in response to a query

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: query_tool_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: query_tool_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: query
          required: true
          description: The user's query as a string
          type: string
      responses:
        '200':
          description: Prediction performed successfully
        '500':
          description: Unable to perform the prediction
