# -*- coding: utf-8 -*-
"""ResearchPaperReadAndSplit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WIwbZ7WACOGiXF4WI5SpYWzRA5Thn25q
"""

###pip install tika

from tika import parser
import glob
import re
print(glob.glob('*/'))
for research_paper_name in glob.glob('/content/*.pdf'):
  print(research_paper_name)
  research_paper_data = parser.from_file(research_paper_name)
  research_paper_content = research_paper_data['content']
  paragraphs = research_paper_content.split("\n\n")
  print(paragraphs)
  research_paper_txt_name = research_paper_name.replace("pdf","txt")
  rp_file= open(research_paper_txt_name,"w+")
  edited_paragraphs = []
  for i in range(len(paragraphs)):
    rp_file.write(str(paragraphs[i]))
    if paragraphs[i] != '':
      edited_paragraphs.append(paragraphs[i])
    if len(edited_paragraphs) != 0:
      edited_paragraphs[len(edited_paragraphs)-1] = re.sub(r"\n", "", edited_paragraphs[len(edited_paragraphs)-1] )
  print(edited_paragraphs)
  
  rp_file.close()