swagger: '2.0'
info:
  title: SQueRT
  version: "0.1"
  description:  |
    # The Scientific Query Research Tool
    ---
    <br/>
    **ENTER YOUR QUERY BELOW**
    <br/>

paths:
  /health:
    get:
      summary: Checks the health of the service
      description: Returns the health status of the service
      operationId: query_tool_api.health
      responses:
        '200':
          description: Service is healthy
        '500':
          description: Service is unhealthy

  /predict:
    post:
      summary: Entrypoint to our prediction function
      operationId: query_tool_api.predict
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
        - in: formData
          name: query
          required: true
          description: The user's query as a string
          type: string
        - in: formData
          name: topic
          required: false
          description: The (optional) topic under which to search
          type: string
      responses:
        '200':
          description: Prediction performed successfully
        '500':
          description: Unable to perform the prediction

  /feedback:
    post:
      summary: Accepts user feedback on result
      operationId: query_tool_api.feedback
      consumes:
      - multipart/form-data
      parameters:
        - in: formData
          name: ranking
          required: false
          description: How did we do? Please select optional feedback for our service
          type: string
          enum: ['Unhelpful', 'Somewhat helpful', 'Helpful']
      responses:
        '200':
          description: Feedback submitted successfully
        '500':
          description: Unable to save feedback